apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: confiance-sandrine-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.8.3
          envFrom:
            - configMapRef:
                name: mariadb-env
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
            - name: mariadb-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: mariadb-initdb
          configMap:
            name: mariadb-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: confiance-sandrine-v1
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
